doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'
        
        profiling_collect_backtrace: '%kernel.debug%'
        
        # Оптимизации подключения к БД
        options:
            1002: "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))" # MySQL
        
        # Настройки для PostgreSQL
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        
        # Оптимизации ORM
        auto_generate_proxy_classes: false
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        
        # Включаем второй уровень кэша
        second_level_cache:
            enabled: true
            default_lifetime: 3600
            default_lock_lifetime: 60
            file_lock_region_directory: '%kernel.cache_dir%/doctrine/orm/slc/filelock'
            regions:
                user_cache:
                    lifetime: 7200
                    cache_driver:
                        type: pool
                        pool: doctrine.second_level_cache_pool
                task_cache:
                    lifetime: 1800
                    cache_driver:
                        type: pool
                        pool: doctrine.second_level_cache_pool
        
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@dev:
    doctrine:
        orm:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool

    framework:
        cache:
            pools:
                doctrine.system_cache_pool:
                    adapter: cache.app

when@prod:
    doctrine:
        orm:
            metadata_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
            # Включаем автогенерацию прокси только в dev
            auto_generate_proxy_classes: false

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                    default_lifetime: 3600
                doctrine.system_cache_pool:
                    adapter: cache.system
                    default_lifetime: 86400
                doctrine.second_level_cache_pool:
                    adapter: cache.app
                    default_lifetime: 3600
