# Redis Cache Configuration
# Использование: composer require predis/predis

framework:
    cache:
        app: cache.adapter.array
        
        # pools:
        #     cache.task:
        #         adapter: cache.adapter.redis
        #         default_lifetime: 3600

when@dev:
    framework:
        cache:
            app: cache.adapter.array
